# Generated by Django 2.2.1 on 2019-06-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20190605_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_original_date',
            field=models.IntegerField(),
        ),
    ]
